{{- $fullName := include "falcosidekick.fullname" . -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "falcosidekick.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
  {{- range $key, $val := .Values.sealedSecret.secrets }}
    {{ $key }}: {{ $val }}
  {{- end }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ include "falcosidekick.fullname" . }}
      namespace: {{ .Release.Namespace }}
    type: Opaque