apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ template "falco.fullname" . }}-gcp-service-account
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
  {{- range $key, $val := .Values.gkeAuditBridge.secrets }}
    {{ $key }}: {{ $val }}
  {{- end }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ template "falco.fullname" . }}-gcp-service-account
      namespace: {{ .Release.Namespace }}
    type: Opaque